Get all queues
openmrs/openmrs-module-queue pull request #15
Opened 2022-11-17 09:32 UTC by CynthiaKamau

2022-11-17 11:01 UTC, dkayiwa commented
@CynthiaKamau do you mind creating a ticket for these changes in this JIRA project? https://issues.openmrs.org/projects/PQ

2022-11-17 11:29 UTC, CynthiaKamau commented
> @CynthiaKamau do you mind creating a ticket for these changes in this JIRA project? https://issues.openmrs.org/projects/PQ

Done

2022-11-17 11:38 UTC, dkayiwa commented
Can you include the ticket url as advised here? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

2022-11-17 12:16 UTC, corneliouzbett reviewed
Thanks, @CynthiaKamau for working on this.
Could you please add tests for this change otherwise LGTM.

2022-11-23 15:26 UTC, CynthiaKamau commented
> Thanks, @CynthiaKamau for working on this. Could you please add tests for this change otherwise LGTM.

Done

2022-11-24 09:05 UTC, corneliouzbett requested changes

2022-11-24 09:05 UTC, corneliouzbett commented on omod/src/test/java/org/openmrs/module/queue/web/resources/QueueResourceTest.java
> +		assertThat(queueService, notNullValue());
Do this instead;
```java
Queue queueMock = mock(Queue.class);

when(queueService.getAllQueues()).thenReturn(Collections.singletonList(queueMock));

Collection<Queue> result = queueService.getAllQueues();
assertThat(result, hasSize(1));
assertThat(result, hasItem(queueMock));
```

2022-11-24 13:55 UTC, corneliouzbett approved these changes
Thanks @CynthiaKamau!

2022-11-24 13:56 UTC, merged